'''
This module uses the APOD and RAG classes to fetch NASA's APOD and generate a
better description of the photo using RAG with summaries of key terms from
Wikipedia.
'''
from datetime import datetime
from apod import APOD
from rag import RAG
import wiki


# NASA APOD API key
API_KEY = 'fqcNkhHmYA1gGSD6HisapBQ30Ig6c8pehkaobn2r'

def run_rag(date: str = None):
    '''
    Fetches NASA APOD for <date> and uses RAG to generate a more descriptive/
    informative explanation of the picture. Will write the original description
    and the explanation produced via RAG to 'results.txt' as well as print to
    the terminal.

    Arguments:
    date: str = 'YYYY-MM-DD'
    '''

    # If no date provided, use today's date formatted as 'YYYY-MM-DD'
    if date is None:
        date = datetime.today()
        date = datetime.strftime(date, "%Y-%m-%d")

    # Instantiate APOD class and fetch image info
    apod = APOD(api_key = API_KEY)
    apod_info = apod.fetch_apod(date)

    # Original description of the image provided by NASA
    photo_explanation = apod_info['explanation']

    # Filename to log information
    RESULTS_FILE = 'results.txt'

    # Write image description to file and print to terminal
    info_output = 'Original APOD Image Information:\n\n' + photo_explanation
    info_output += '\n\n'

    with open(RESULTS_FILE,'w') as f:
        f.write(info_output)
    print(info_output)
    
    # Instantiate RAG class and generate lookup list
    rag = RAG('llama3.2')
    lookup_list = rag.generate_lookup_list(photo_explanation, RESULTS_FILE)

    # For all generated lookups, fetch wikipedia summary and create prompt info
    # for model to create a new description
    all_item_summaries = ''
    for item in lookup_list:
        summary = wiki.fetch_wikipedia_summary(item, RESULTS_FILE)
        all_item_summaries += f'{item}: {summary}'
        if not all_item_summaries.endswith('\n'):
            all_item_summaries += '\n'
    
    # Feed wikipedia summary info to model to create a new description of the
    # photo
    augmented_description = rag.generate_augmented_description(apod_info,
                                                               all_item_summaries)
    
    # Print new description generated by model to terminal and write to file
    rag_output = f'\nRAG Generated Description:\n\n'+augmented_description
    print(rag_output)
    with open(RESULTS_FILE, 'a') as f:
        f.write(rag_output)
        f.write('\n\nLink to this photo:\n')

    # Fetch image url and write it to file (under normal circumstances...)
    apod.download_image(RESULTS_FILE)

    
if __name__ == '__main__':
    run_rag('2024-12-14')